name: Remote Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: remote-build-ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-simulator:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Rock Remote Build - iOS simulator
        uses: callstackincubator/ios@v3
        with:
          destination: simulator
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scheme: GOSIM
          configuration: Debug # replace with preferred configuration
